\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename FAQ.info
@settitle vmailmgr Frequently Asked Questions
@setchapternewpage off
@paragraphindent 5
@c %**end of header
@footnotestyle end

@ifinfo
Copyright @copyright{} 1998 Bruce Guenter
@end ifinfo

@titlepage
@title vmailmgr Frequently Asked Questions
@author Bruce Guenter
@subtitle @today{}
@end titlepage

@node Top, Building and Installing, (dir), (dir)

@menu
* Building and Installing::     
* Setup and Configuration::     
* Usage::                       
* Troubleshooting::             
* Miscelaneous::                
@end menu

@c ****************************************************************************
@node Building and Installing, Setup and Configuration, Top, Top
@chapter Building and Installing

@menu
* What compiler and libraries do I need to build vmailmgr?::  
* Does vmailmgr work with shadow passwords?::  
@end menu

@c ============================================================================
@node What compiler and libraries do I need to build vmailmgr?, Does vmailmgr work with shadow passwords?, Building and Installing, Building and Installing
@section What compiler and libraries do I need to build vmailmgr?

You will need a working C and C++ compiler and linker.
You will not need any C++ libraries.

The package is being developed under Linux using
egcs and glibc version 2, and may rely on some
gcc/g++ extensions.

@c ============================================================================
@node Does vmailmgr work with shadow passwords?,  , What compiler and libraries do I need to build vmailmgr?, Building and Installing
@section Does vmailmgr work with shadow passwords?

This package should work without changes both with and without shadow
passwords as long as the shadow password libraries are present when this
package is built.
The @file{configure} script will detect what method of shadow passwords
are being used and the programs will be built accordingly.

@c ****************************************************************************
@node Setup and Configuration, Usage, Building and Installing, Top
@chapter Setup and Configuration

@menu
* What other software is needed to run vmailmgr?::  
* How do I record the output of vmailmgrd with syslog?::  
* How do I record the output of vmailmgrd with accustamp/cyclog?::  
* Upgrading from Previous Versions::  
@end menu

@c ============================================================================
@node What other software is needed to run vmailmgr?, How do I record the output of vmailmgrd with syslog?, Setup and Configuration, Setup and Configuration
@section What other software is needed to run vmailmgr?

vmailmgr is based around qmail's handling of virtual users, and as such
requires qmail for its operation.
If you wish to use the @file{init} file to start/stop vmailmgrd or are
installing the RPM package, a patched version of the daemontools 0.53
(or later) package is required (available at
@file{http://em.ca/~bruceg/rpms/daemontools/}).

@c ============================================================================
@node How do I record the output of vmailmgrd with syslog?, How do I record the output of vmailmgrd with accustamp/cyclog?, What other software is needed to run vmailmgr?, Setup and Configuration
@section How do I record the output of vmailmgrd with syslog?

Output from vmailmgrd can be recorded by either splogger (part of
qmail) or with the logger that comes with several flavours of UNIX.
To use splogger, pipe the output of vmailmgrd into the command
@samp{splogger vmailmgrd}.
This will timestamp each entry and tag them with the word
@samp{vmailmgrd}.
By default, splogger logs to facility 2 (mail).
To use logger, pipe the output of vmailmgrd into the comamand
@samp{logger -t vmailmgrd -p mail.notice}.
See the respective man pages of these two programs for more information.

@c ============================================================================
@node How do I record the output of vmailmgrd with accustamp/cyclog?, Upgrading from Previous Versions, How do I record the output of vmailmgrd with syslog?, Setup and Configuration
@section How do I record the output of vmailmgrd with accustamp/cyclog?

Make a directory into which the output will go, for example
@file{/var/log/vmailmgrd}.
Pipe the output of vmailmgrd into the command @samp{accustamp | cyclog
/var/log/vmailmgrd}.
See the man page for cyclog for more information on how to adjust its
output.

@c ============================================================================
@node  Upgrading from Previous Versions,  , How do I record the output of vmailmgrd with accustamp/cyclog?, Setup and Configuration
@section Upgrading from Previous Versions

If you are upgrading from an older version, you may need to make some
changes to your system before or after doing the upgrade.
The following table outlines the necessary changes.
Note that you need to follow the instructions for all later versions of
the software.

If you are upgrading from version:

@table @strong

@item 0.96.2 or earlier

Make sure the @file{vmailmgrd} daemon and vmailmgr CGIs are disabled
before upgrading, and upgrade them along with the main package.
Changes were made to the daemon interface that will cause adding users
and aliases to flake out.
As well, the listdomain interface was completely redone.

@item 0.94 or earlier, using the POP bulletin facility

The POP bulletin facility has been moved into a stand-alone program that
needs to be executed through @file{checkvpw-postsetuid}.

@item 0.93 or earlier

If you do not use the CGIs, you no longer need to run the
@file{vmailmgrd} daemon.

@item 0.92.2 or earlier

The configuration changed from reading a single file to reading a set of
files in a directory.
Read the configuration documentation and run the program
@file{vconf2dir}.

@item 0.90.2 or earlier

The name of the user to which mail to an unknown user is delivered
changed from @samp{*} to @samp{+}.
If you were using this feature, either change all your domains to
accomodate this change, or set the @file{default-username} config
file to contain @samp{*}.

@item 0.88 or earlier

The file format of the virtual password tables has changed from plain
text files to CDB tables.
You will need to suspend local deliveries before upgrading, and run the
program @file{vpasswd2cdb} as each base user after upgrading, before
re-enabling local deliveries.

@end table

@c ****************************************************************************
@node Usage, Troubleshooting, Setup and Configuration, Top
@chapter Usage

@menu
* I can only use one IP address.  How do I log in as a virtual user?::  
* How do I get all misdirected mail sent to me?::  
@end menu

@c ============================================================================
@node I can only use one IP address.  How do I log in as a virtual user?, How do I get all misdirected mail sent to me?, Usage, Usage
@section I can only use one IP address.  How do I log in as a virtual user?

There are two ways to log in without using multiple IP addresses.

The first way is to log in as @samp{user@var{SEP}virtual.domain.org},
where @samp{user} is the mailbox name of the virtual user, @var{SEP} is
one of @samp{@@} or @samp{:} (by default, this is configurable in the
@file{/etc/vmailmgr/} directory), and @samp{virtual.domain.org} is the
virtual domain's name, as listed in
@file{/var/qmail/control/virtualdomains}.

The second way is to use the internal form of the mailbox name -- that
is, @samp{baseuser-user}, where @samp{user} is the same as above, and
@samp{baseuser} is the username of the managing user.

Example: @file{/var/qmail/control/virtualdomains} contains
@example
testdomain.org:testuser
@end example
User @samp{testuser} exists, and has set up a virtual mailbox with the
name @samp{v}.  The @samp{separators} variable in
@file{/etc/vmailmgr/} contains @samp{@@:}.
This virtual user could log in as @samp{v@@testdomain.org},
@samp{v:testdomain.org}, or @samp{testuser-v}.

@c ============================================================================
@node How do I get all misdirected mail sent to me?,  , I can only use one IP address.  How do I log in as a virtual user?, Usage
@section How do I get all misdirected mail sent to me?

In the @file{vmailmgr/} configuration directory, there is an entry called
@samp{default-username}.
If mail to a virtual domain does not match any users or aliases in that
domain, it is delivered to the name listed in this configuration item if
it exists (which defaults to @samp{+}).
To make this deliver to you, simply type:
@example
vaddalias me +
@end example

@c ****************************************************************************
@node Troubleshooting, Miscelaneous, Usage, Top
@chapter Troubleshooting

@menu
* Bind error message from vmailmgrd.::  
@end menu

@c ============================================================================
@node Bind error message from vmailmgrd.,  , Troubleshooting, Troubleshooting
@section Bind error message from vmailmgrd.

If vmailmgrd reports @samp{vmailmgrd: bind: no such file or directory}
when you start it up, it means that can't create its socket file.
By default, it will try to create the socket file
@file{/tmp/.vmailmgrd}.
You must ensure that @file{/tmp} is writable, or that the socket is
created in some other place by setting @file{socket-file} in the
configuration.

@c ****************************************************************************
@node Miscelaneous,  , Troubleshooting, Top
@chapter Miscelaneous

@menu
* How do I get in contact with other users?::  
* Does vmailmgr support IMAP?::  
* How does incoming email get handled?::  
* How does outgoing email get handled?::  
@end menu

@c ============================================================================
@node How do I get in contact with other users?, Does vmailmgr support IMAP?, Miscelaneous, Miscelaneous
@section How do I get in contact with other users?

There is a mailing list run by the author.
To subscribe, send an e-mail (content and subject line is ignored) to
@samp{vmailmgr-subscribe@@lists.em.ca}.

Remember that if you have a problem that you want us to diagnose, we
need to know the following important details:
@enumerate
@item The output of `qmail-showctl`
@item The contents of the vmailmgrd log for the attempt you are trying
to diagnose
@item The contents of the qmail and smtpd logs for a failed delivery
attempt
@item The contents of the pop3d logs for a failed login attempt
@item The complete command line with which vmailmgrd and qmail-pop3d was invoked
@end enumerate

Please do not contact the author directly with vmailmgr questions.

@c ============================================================================
@node Does vmailmgr support IMAP?, How does incoming email get handled?, How do I get in contact with other users?, Miscelaneous
@section Does vmailmgr support IMAP?

Yes, vmailmgr supports Courier IMAP.
The default installation of vmailmgr installs a Courier IMAP
authentication module in
@file{/usr/local/lib/courier-imap/libexec/authlib/authvmailmgr}
(assuming @samp{prefix} is left as @file{/usr/local}).
You must then copy the above file to wherever your installation of
Courier IMAP expects to find authentication modules (typically
@file{/usr/lib/courier-imap/libexec/authlib}).
If you have changed @samp{prefix} to @file{/usr} when running
@file{configure}, no copying should be necessary.
Finally modify the @samp{AUTHMODULES} statement in
@file{/usr/lib/courier-imap/etc/imapd.config} and add authvmailmgr as
the first authentication module.
If you are installing from RPMs, the @file{vmailmgr-courier-imap}
package will install the authentication module into the right place.

For more information on Courier IMAP, go to its web site at
@file{http://www.inter7.com/courierimap/}.

@c ============================================================================
@node How does incoming email get handled?, How does outgoing email get handled?, Does vmailmgr support IMAP?, Miscelaneous
@section How does incoming email get handled?

Incoming email is first received by the qmail SMTP daemon and inserted
into the qmail queue.
Then @file{qmail-send} examines the email envelope (which details the
recipient address or addresses) to determine how to dispatch the
message.
It looks up the domain name of each recipient in
@file{/var/qmail/control/virtualdomains}, and prefixes the user name
with the string that it finds.
It then looks up the resulting user name in the system password table
(or in @file{/var/qmail/users/cdb} if it exists) to find the base user
name and home directory (which I will call @file{$HOME}).
It then looks for the file @file{$HOME/.qmail-VIRTUAL}.
If that's not found, it looks for the file @file{$HOME/.qmail-default},
which will contain an instruction to pipe the message to @file{vdeliver}.

This is where vmailmgr first enters the picture.
The virtual user name is sent to @file{vdeliver} through environment
variables.
It looks in the configuration files (in @file{$HOME/.vmailmgr} and then
in @file{/etc/vmailmgr}) to determine the location of the password
table, and looks up the virtual user name in the table to determine
delivery instructions.
If the name is not found, the message is bounced and delivery ends.
Otherwise, it then looks for the @file{vdeliver-predeliver} script in the
configuration directories (in reverse order) and executes any that are
found.
It then delivers the message to all the listed destinations -- an
optional mailbox directory and zero or more forwarding addresses.
Finally, it looks for the @file{vdeliver-postdeliver} script and
executes any that are found.

@c ============================================================================
@node How does outgoing email get handled?,  , How does incoming email get handled?, Miscelaneous
@section How does outgoing email get handled?

Outgoing email is not handled by vmailmgr.
For details on outgoing email handling, check the qmail documentation.

@bye
