\input texinfo @c -*-texinfo-*-
@c %**start of header
@setfilename HOWTO.info
@settitle Vmailmgr HOWTO
@setchapternewpage off
@paragraphindent 5
@c %**end of header
@footnotestyle end

@ifinfo
Copyright @copyright{} 1998 Bruce Guenter
@end ifinfo

@titlepage
@title Vmailmgr HOWTO
@author Bruce Guenter
@subtitle @today{}
@end titlepage

@node Top, Setup, (dir), (dir)

@menu
* Setup::                       
@end menu

@c ****************************************************************************
@node Setup,  , Top, Top
@chapter Setup

@menu
* Setting Up a Virtual Domain::  
@end menu

@c ============================================================================
@node Setting Up a Virtual Domain,  , Setup, Setup
@section Setting Up a Virtual Domain

The following steps are necessary to set up a virtual domain with
vmailmgr (assuming vmailmgr has been compiled and installed).
As an example, we'll set up a virtual user @samp{me@@mydomain.org}, with
aliases of @samp{myself@@mydomain.org} and @samp{i@@mydomain.org}.

@enumerate
@item Set up a DNS entry for the domain.

I won't cover this here, as it is dependant on far too many other things.
For the example, we'll assume that the mail exchanger for mydomain.org
is already set up to point to your computer.

@item Set up a base user for the domain.

Create a user, with a name of your choosing.  Since the maildirs for all
the users in the virtual domain will be stored under this user's home
directory, make sure you set the user up in a partition or disk that is
appropriate for such storage.
The tools that you should use to accomplish this step vary greatly
between different systems.
For our example, I'll add a user @samp{mo}.

@item Configure qmail to recognize the domain.

To do this, you need to modify two of qmail's configuration files in
@file{/var/qmail/control}: @file{rcpthosts} and @file{virtualdomains}.
To @file{rcpthosts}, add the line @samp{mydomain.org}.
To @file{virtualdomains}, add the line @samp{mydomain.org:mo}.
If you wish to have mail to @samp{anything.mydomain.org} be delivered in
the same way, add the line @samp{.mydomain.org} to @file{rcpthosts} and
add the line @samp{.mydomain.org:mo} to @file{virtualdomains}.

@item Configure qmail-popup/qmail-pop3d to use checkvpw as the password
checker.

This step is dependant on how you have installed qmail, but is typically
as simple as replacing @samp{checkpassword} in the command you use to
invoke qmail-popup/qmail-pop3d (either in @file{/etc/inet.conf} or in a
@samp{tcpserver} command) with @samp{checkvpw}.

@item Add users or aliases to the domain.

Either change user to the user you just created (for example, type
@samp{su - mo}) or log in (with either telnet or at the console) as the
new user, and use the included programs to add users and aliases.
For our example, we would type @samp{vadduser me} (which prompts for a
password), @samp{vaddalias me myself}, and @samp{vaddalias me i}.

@end enumerate

After you have completed all these steps, you will need to kill and
restart @file{qmail-send} to make it read the new @file{virtualdomains}
table.
If you are using @samp{inetd} to launch @samp{qmail-popup},
@samp{kill -HUP} the @samp{inetd} process as well.

@c ****************************************************************************
@contents

@bye
