=head1 NAME

vdeliver - deliver an e-mail message via vmailmgr

=head1 SYNOPSIS

B<vdeliver> [B<-dfrDFR>]

=head1 DESCRIPTION

vdeliver is the unified e-mail message delivery agent for virtual
domains managed by vmailmgr.
It is run from the F<.qmail-default> file, and automatically handles
delivery to any user within a virtual domain.

=head1 OPTIONS

=over 8

=item -d

Do not add the C<Delivered-To:> line to the top of the message.

=item -f

(default) Do not add the C<From> mailbox line to the top of the message.
Note that this line is never added when the message is being
re-injected into the mail stream.

=item -r

Do not add the C<Return-Path:> line to the top of the message.

=item -D

(default) Add the C<Delivered-To:> line to the top of the message.

=item -F

Add the C<From> mailbox line to the top of the message.

=item -R

(default) Add the C<Return-Path:> line to the top of the message.

=back

=head1 RETURN VALUE

Returns 0 if delivery was successful,
100 if a fatal error occurred,
or 111 if a temporary error occurred.

=head1 ENVIRONMENT

F<vdeliver> expects to be run by F<qmail-local> as it requires several
of the environment variables that it sets.
See the I<qmail-command>(8) manual page for full details on these
variables.
In particular, it requires C<DTLINE>, C<EXT>, C<HOST>, C<RPLINE>,
C<SENDER>, C<UFLINE>, and C<USER>.

=head1 SEE ALSO

checkvpw(1), I<qmail-command>(8)

=head1 AUTHOR

Bruce Guenter <F<bruceg@em.ca>>.

