=head1 NAME

vdeluser - delete a virtual user

=head1 SYNOPSIS

B<vdeluser> B<username> [B<username> ...]

=head1 DESCRIPTION

This program will take the steps necessary to
remove a user from a virtual domain.

For each user listed on the command line, it does the following:

=over 8

=item 1

It removes the named user's entry from the local password file.

=item 2

It removes any qmail delivery files that point to the named user's
mail directory.

=item 3

It removes the user's mail directory and all of its contents
(recursively).

=back

If any of the above steps fail, a warning is issued and processing
continues.

=head1 NOTES

You must have either created the users subdirectory by hand or run the
F<vsetup> program before using this program.

This program expects the environment variable C<HOME> to be set, and
executes a change directory to the contents of it before starting.  It
is also required that you change user to the domain owner before using
these utilities.

=head1 AUTHOR

Bruce Guenter <F<bruceg@em.ca>>.
