=head1 NAME

vpasswds - change a list of virtual users' passwords

=head1 SYNOPSIS

B<vpasswds>

=head1 DESCRIPTION

This program is used to change the password of a list of virtual
users.  The list is taken from standard input and is of the form:

	username password

It will attempt to change the password for each listed user.
If any step fails, a warning is issued and processing continues with
the next line.
Any input folling the password is ignored.

=head1 SEE ALSO

vpasswd(1)

=head1 NOTES

You must have either created the users subdirectory by hand or run the
F<vsetup> program before using this program.

This program expects the environment variable C<HOME> to be set, and
executes a change directory to the contents of it before starting.  It
is also required that you change user to the domain owner before using
these utilities.

=head1 AUTHOR

Bruce Guenter <F<bruceg@em.ca>>.
