=head1 NAME

vsetup - set up a virtual domain

=head1 SYNOPSYS

B<vsetup>

=head1 DESCRIPTION

This program sets up the basic set of necessary files needed to use an
account as a virtual domain with vmailmgr.
The users directory is created if it does not exist.
A F<.qmail-default> file is created with the proper contents.
If a F<.qmail-default> previously existed, it is renamed to
F<.qmail-default~>.
Three system aliases (C<root>, C<mailer-daemon>, and C<postmaster>)
are created to point to the configured postmaster.

=head1 RETURN VALUE

0 if all files and directories are successfully created, 1 otherwise.

=head1 SEE ALSO

vdeliver(1), vmailmgrd(8)

=head1 NOTES

This program expects the environment variable C<HOME> to be set, and
executes a change directory to the contents of it before starting.  It
is also required that you change user to the domain owner before using
these utilities.

=head1 AUTHOR

Bruce Guenter <F<bruceg@em.ca>>.
