#!/bin/sh
#
# vmailmgrd	This shell script takes care of starting and stopping
#		vmailmgrd (virtual mail manager daemon)
#
# chkconfig: 345 65 35
# description: vmailmgrd is the daemon required for the vmailmgr package
# to work properly.

# Source function library.
. /etc/rc.d/init.d/functions

# See how we were called.
case "$1" in
  start)
	svc-start vmailmgrd
        ;;
  stop)
	svc-stop vmailmgrd
        ;;
  status)
	svc-status vmailmgrd
	;;
  restart)
	"$0" stop
	sleep 1
	"$0" start
	;;
  *)
        echo "Usage: vmailmgrd {start|stop|restart|status}"
        exit 1
esac

exit 0
